// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        v6.33.4
// source: grpc/user-service.proto

package photopro_user_service

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	emptypb "google.golang.org/protobuf/types/known/emptypb"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type Location struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Name          *string                `protobuf:"bytes,1,opt,name=name" json:"name,omitempty"`
	Street        *string                `protobuf:"bytes,2,opt,name=street" json:"street,omitempty"`
	StreetNumber  *uint32                `protobuf:"varint,3,opt,name=streetNumber" json:"streetNumber,omitempty"`
	Country       *string                `protobuf:"bytes,4,opt,name=country" json:"country,omitempty"`
	FederalState  *string                `protobuf:"bytes,5,opt,name=federalState" json:"federalState,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Location) Reset() {
	*x = Location{}
	mi := &file_grpc_user_service_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Location) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Location) ProtoMessage() {}

func (x *Location) ProtoReflect() protoreflect.Message {
	mi := &file_grpc_user_service_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Location.ProtoReflect.Descriptor instead.
func (*Location) Descriptor() ([]byte, []int) {
	return file_grpc_user_service_proto_rawDescGZIP(), []int{0}
}

func (x *Location) GetName() string {
	if x != nil && x.Name != nil {
		return *x.Name
	}
	return ""
}

func (x *Location) GetStreet() string {
	if x != nil && x.Street != nil {
		return *x.Street
	}
	return ""
}

func (x *Location) GetStreetNumber() uint32 {
	if x != nil && x.StreetNumber != nil {
		return *x.StreetNumber
	}
	return 0
}

func (x *Location) GetCountry() string {
	if x != nil && x.Country != nil {
		return *x.Country
	}
	return ""
}

func (x *Location) GetFederalState() string {
	if x != nil && x.FederalState != nil {
		return *x.FederalState
	}
	return ""
}

type Permission struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	UserID        *uint64                `protobuf:"varint,1,opt,name=userID" json:"userID,omitempty"`
	ProjectID     *uint64                `protobuf:"varint,2,opt,name=projectID" json:"projectID,omitempty"`
	RoleID        *uint64                `protobuf:"varint,3,opt,name=RoleID" json:"RoleID,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Permission) Reset() {
	*x = Permission{}
	mi := &file_grpc_user_service_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Permission) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Permission) ProtoMessage() {}

func (x *Permission) ProtoReflect() protoreflect.Message {
	mi := &file_grpc_user_service_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Permission.ProtoReflect.Descriptor instead.
func (*Permission) Descriptor() ([]byte, []int) {
	return file_grpc_user_service_proto_rawDescGZIP(), []int{1}
}

func (x *Permission) GetUserID() uint64 {
	if x != nil && x.UserID != nil {
		return *x.UserID
	}
	return 0
}

func (x *Permission) GetProjectID() uint64 {
	if x != nil && x.ProjectID != nil {
		return *x.ProjectID
	}
	return 0
}

func (x *Permission) GetRoleID() uint64 {
	if x != nil && x.RoleID != nil {
		return *x.RoleID
	}
	return 0
}

type Role struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            *uint64                `protobuf:"varint,1,opt,name=id" json:"id,omitempty"`
	Name          *string                `protobuf:"bytes,2,opt,name=name" json:"name,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Role) Reset() {
	*x = Role{}
	mi := &file_grpc_user_service_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Role) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Role) ProtoMessage() {}

func (x *Role) ProtoReflect() protoreflect.Message {
	mi := &file_grpc_user_service_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Role.ProtoReflect.Descriptor instead.
func (*Role) Descriptor() ([]byte, []int) {
	return file_grpc_user_service_proto_rawDescGZIP(), []int{2}
}

func (x *Role) GetId() uint64 {
	if x != nil && x.Id != nil {
		return *x.Id
	}
	return 0
}

func (x *Role) GetName() string {
	if x != nil && x.Name != nil {
		return *x.Name
	}
	return ""
}

type User struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Username      *string                `protobuf:"bytes,1,opt,name=username" json:"username,omitempty"`
	Email         *string                `protobuf:"bytes,2,opt,name=email" json:"email,omitempty"`
	Password      *string                `protobuf:"bytes,3,opt,name=password" json:"password,omitempty"`
	Location      *Location              `protobuf:"bytes,4,opt,name=location" json:"location,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *User) Reset() {
	*x = User{}
	mi := &file_grpc_user_service_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *User) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*User) ProtoMessage() {}

func (x *User) ProtoReflect() protoreflect.Message {
	mi := &file_grpc_user_service_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use User.ProtoReflect.Descriptor instead.
func (*User) Descriptor() ([]byte, []int) {
	return file_grpc_user_service_proto_rawDescGZIP(), []int{3}
}

func (x *User) GetUsername() string {
	if x != nil && x.Username != nil {
		return *x.Username
	}
	return ""
}

func (x *User) GetEmail() string {
	if x != nil && x.Email != nil {
		return *x.Email
	}
	return ""
}

func (x *User) GetPassword() string {
	if x != nil && x.Password != nil {
		return *x.Password
	}
	return ""
}

func (x *User) GetLocation() *Location {
	if x != nil {
		return x.Location
	}
	return nil
}

type CreateUserRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	User          *User                  `protobuf:"bytes,1,opt,name=user" json:"user,omitempty"`
	Role          *Role                  `protobuf:"bytes,2,opt,name=role" json:"role,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CreateUserRequest) Reset() {
	*x = CreateUserRequest{}
	mi := &file_grpc_user_service_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CreateUserRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CreateUserRequest) ProtoMessage() {}

func (x *CreateUserRequest) ProtoReflect() protoreflect.Message {
	mi := &file_grpc_user_service_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CreateUserRequest.ProtoReflect.Descriptor instead.
func (*CreateUserRequest) Descriptor() ([]byte, []int) {
	return file_grpc_user_service_proto_rawDescGZIP(), []int{4}
}

func (x *CreateUserRequest) GetUser() *User {
	if x != nil {
		return x.User
	}
	return nil
}

func (x *CreateUserRequest) GetRole() *Role {
	if x != nil {
		return x.Role
	}
	return nil
}

type CreateUserResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	User          *User                  `protobuf:"bytes,1,opt,name=user" json:"user,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CreateUserResponse) Reset() {
	*x = CreateUserResponse{}
	mi := &file_grpc_user_service_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CreateUserResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CreateUserResponse) ProtoMessage() {}

func (x *CreateUserResponse) ProtoReflect() protoreflect.Message {
	mi := &file_grpc_user_service_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CreateUserResponse.ProtoReflect.Descriptor instead.
func (*CreateUserResponse) Descriptor() ([]byte, []int) {
	return file_grpc_user_service_proto_rawDescGZIP(), []int{5}
}

func (x *CreateUserResponse) GetUser() *User {
	if x != nil {
		return x.User
	}
	return nil
}

type GetUserRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	UserID        *uint64                `protobuf:"varint,1,opt,name=userID" json:"userID,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetUserRequest) Reset() {
	*x = GetUserRequest{}
	mi := &file_grpc_user_service_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetUserRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetUserRequest) ProtoMessage() {}

func (x *GetUserRequest) ProtoReflect() protoreflect.Message {
	mi := &file_grpc_user_service_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetUserRequest.ProtoReflect.Descriptor instead.
func (*GetUserRequest) Descriptor() ([]byte, []int) {
	return file_grpc_user_service_proto_rawDescGZIP(), []int{6}
}

func (x *GetUserRequest) GetUserID() uint64 {
	if x != nil && x.UserID != nil {
		return *x.UserID
	}
	return 0
}

type GetUserResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	User          *User                  `protobuf:"bytes,1,opt,name=user" json:"user,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetUserResponse) Reset() {
	*x = GetUserResponse{}
	mi := &file_grpc_user_service_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetUserResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetUserResponse) ProtoMessage() {}

func (x *GetUserResponse) ProtoReflect() protoreflect.Message {
	mi := &file_grpc_user_service_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetUserResponse.ProtoReflect.Descriptor instead.
func (*GetUserResponse) Descriptor() ([]byte, []int) {
	return file_grpc_user_service_proto_rawDescGZIP(), []int{7}
}

func (x *GetUserResponse) GetUser() *User {
	if x != nil {
		return x.User
	}
	return nil
}

type UpdateUserRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	UserID        *uint64                `protobuf:"varint,1,opt,name=userID" json:"userID,omitempty"`
	Email         *string                `protobuf:"bytes,2,opt,name=email" json:"email,omitempty"`
	Password      *string                `protobuf:"bytes,3,opt,name=password" json:"password,omitempty"`
	Location      *Location              `protobuf:"bytes,4,opt,name=location" json:"location,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *UpdateUserRequest) Reset() {
	*x = UpdateUserRequest{}
	mi := &file_grpc_user_service_proto_msgTypes[8]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UpdateUserRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UpdateUserRequest) ProtoMessage() {}

func (x *UpdateUserRequest) ProtoReflect() protoreflect.Message {
	mi := &file_grpc_user_service_proto_msgTypes[8]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UpdateUserRequest.ProtoReflect.Descriptor instead.
func (*UpdateUserRequest) Descriptor() ([]byte, []int) {
	return file_grpc_user_service_proto_rawDescGZIP(), []int{8}
}

func (x *UpdateUserRequest) GetUserID() uint64 {
	if x != nil && x.UserID != nil {
		return *x.UserID
	}
	return 0
}

func (x *UpdateUserRequest) GetEmail() string {
	if x != nil && x.Email != nil {
		return *x.Email
	}
	return ""
}

func (x *UpdateUserRequest) GetPassword() string {
	if x != nil && x.Password != nil {
		return *x.Password
	}
	return ""
}

func (x *UpdateUserRequest) GetLocation() *Location {
	if x != nil {
		return x.Location
	}
	return nil
}

type UpdateUserResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	User          *User                  `protobuf:"bytes,1,opt,name=user" json:"user,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *UpdateUserResponse) Reset() {
	*x = UpdateUserResponse{}
	mi := &file_grpc_user_service_proto_msgTypes[9]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UpdateUserResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UpdateUserResponse) ProtoMessage() {}

func (x *UpdateUserResponse) ProtoReflect() protoreflect.Message {
	mi := &file_grpc_user_service_proto_msgTypes[9]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UpdateUserResponse.ProtoReflect.Descriptor instead.
func (*UpdateUserResponse) Descriptor() ([]byte, []int) {
	return file_grpc_user_service_proto_rawDescGZIP(), []int{9}
}

func (x *UpdateUserResponse) GetUser() *User {
	if x != nil {
		return x.User
	}
	return nil
}

type DeleteUserRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	UserID        *uint64                `protobuf:"varint,1,opt,name=userID" json:"userID,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *DeleteUserRequest) Reset() {
	*x = DeleteUserRequest{}
	mi := &file_grpc_user_service_proto_msgTypes[10]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DeleteUserRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DeleteUserRequest) ProtoMessage() {}

func (x *DeleteUserRequest) ProtoReflect() protoreflect.Message {
	mi := &file_grpc_user_service_proto_msgTypes[10]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DeleteUserRequest.ProtoReflect.Descriptor instead.
func (*DeleteUserRequest) Descriptor() ([]byte, []int) {
	return file_grpc_user_service_proto_rawDescGZIP(), []int{10}
}

func (x *DeleteUserRequest) GetUserID() uint64 {
	if x != nil && x.UserID != nil {
		return *x.UserID
	}
	return 0
}

type DeleteUserResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Username      *string                `protobuf:"bytes,1,opt,name=username" json:"username,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *DeleteUserResponse) Reset() {
	*x = DeleteUserResponse{}
	mi := &file_grpc_user_service_proto_msgTypes[11]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DeleteUserResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DeleteUserResponse) ProtoMessage() {}

func (x *DeleteUserResponse) ProtoReflect() protoreflect.Message {
	mi := &file_grpc_user_service_proto_msgTypes[11]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DeleteUserResponse.ProtoReflect.Descriptor instead.
func (*DeleteUserResponse) Descriptor() ([]byte, []int) {
	return file_grpc_user_service_proto_rawDescGZIP(), []int{11}
}

func (x *DeleteUserResponse) GetUsername() string {
	if x != nil && x.Username != nil {
		return *x.Username
	}
	return ""
}

type CreateRolesRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Rolename      *string                `protobuf:"bytes,1,opt,name=rolename" json:"rolename,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CreateRolesRequest) Reset() {
	*x = CreateRolesRequest{}
	mi := &file_grpc_user_service_proto_msgTypes[12]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CreateRolesRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CreateRolesRequest) ProtoMessage() {}

func (x *CreateRolesRequest) ProtoReflect() protoreflect.Message {
	mi := &file_grpc_user_service_proto_msgTypes[12]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CreateRolesRequest.ProtoReflect.Descriptor instead.
func (*CreateRolesRequest) Descriptor() ([]byte, []int) {
	return file_grpc_user_service_proto_rawDescGZIP(), []int{12}
}

func (x *CreateRolesRequest) GetRolename() string {
	if x != nil && x.Rolename != nil {
		return *x.Rolename
	}
	return ""
}

type CreateRolesResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Role          *Role                  `protobuf:"bytes,1,opt,name=role" json:"role,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CreateRolesResponse) Reset() {
	*x = CreateRolesResponse{}
	mi := &file_grpc_user_service_proto_msgTypes[13]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CreateRolesResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CreateRolesResponse) ProtoMessage() {}

func (x *CreateRolesResponse) ProtoReflect() protoreflect.Message {
	mi := &file_grpc_user_service_proto_msgTypes[13]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CreateRolesResponse.ProtoReflect.Descriptor instead.
func (*CreateRolesResponse) Descriptor() ([]byte, []int) {
	return file_grpc_user_service_proto_rawDescGZIP(), []int{13}
}

func (x *CreateRolesResponse) GetRole() *Role {
	if x != nil {
		return x.Role
	}
	return nil
}

type ListRolesResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Roles         []*Role                `protobuf:"bytes,1,rep,name=roles" json:"roles,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListRolesResponse) Reset() {
	*x = ListRolesResponse{}
	mi := &file_grpc_user_service_proto_msgTypes[14]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListRolesResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListRolesResponse) ProtoMessage() {}

func (x *ListRolesResponse) ProtoReflect() protoreflect.Message {
	mi := &file_grpc_user_service_proto_msgTypes[14]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListRolesResponse.ProtoReflect.Descriptor instead.
func (*ListRolesResponse) Descriptor() ([]byte, []int) {
	return file_grpc_user_service_proto_rawDescGZIP(), []int{14}
}

func (x *ListRolesResponse) GetRoles() []*Role {
	if x != nil {
		return x.Roles
	}
	return nil
}

type UpdateRolesRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	RoleID        *uint64                `protobuf:"varint,1,opt,name=roleID" json:"roleID,omitempty"`
	RoleName      *uint64                `protobuf:"varint,2,opt,name=roleName" json:"roleName,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *UpdateRolesRequest) Reset() {
	*x = UpdateRolesRequest{}
	mi := &file_grpc_user_service_proto_msgTypes[15]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UpdateRolesRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UpdateRolesRequest) ProtoMessage() {}

func (x *UpdateRolesRequest) ProtoReflect() protoreflect.Message {
	mi := &file_grpc_user_service_proto_msgTypes[15]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UpdateRolesRequest.ProtoReflect.Descriptor instead.
func (*UpdateRolesRequest) Descriptor() ([]byte, []int) {
	return file_grpc_user_service_proto_rawDescGZIP(), []int{15}
}

func (x *UpdateRolesRequest) GetRoleID() uint64 {
	if x != nil && x.RoleID != nil {
		return *x.RoleID
	}
	return 0
}

func (x *UpdateRolesRequest) GetRoleName() uint64 {
	if x != nil && x.RoleName != nil {
		return *x.RoleName
	}
	return 0
}

type UpdateRolesResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Role          *Role                  `protobuf:"bytes,1,opt,name=role" json:"role,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *UpdateRolesResponse) Reset() {
	*x = UpdateRolesResponse{}
	mi := &file_grpc_user_service_proto_msgTypes[16]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UpdateRolesResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UpdateRolesResponse) ProtoMessage() {}

func (x *UpdateRolesResponse) ProtoReflect() protoreflect.Message {
	mi := &file_grpc_user_service_proto_msgTypes[16]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UpdateRolesResponse.ProtoReflect.Descriptor instead.
func (*UpdateRolesResponse) Descriptor() ([]byte, []int) {
	return file_grpc_user_service_proto_rawDescGZIP(), []int{16}
}

func (x *UpdateRolesResponse) GetRole() *Role {
	if x != nil {
		return x.Role
	}
	return nil
}

type ListPermissionsRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	UserID        *uint64                `protobuf:"varint,1,opt,name=userID" json:"userID,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListPermissionsRequest) Reset() {
	*x = ListPermissionsRequest{}
	mi := &file_grpc_user_service_proto_msgTypes[17]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListPermissionsRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListPermissionsRequest) ProtoMessage() {}

func (x *ListPermissionsRequest) ProtoReflect() protoreflect.Message {
	mi := &file_grpc_user_service_proto_msgTypes[17]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListPermissionsRequest.ProtoReflect.Descriptor instead.
func (*ListPermissionsRequest) Descriptor() ([]byte, []int) {
	return file_grpc_user_service_proto_rawDescGZIP(), []int{17}
}

func (x *ListPermissionsRequest) GetUserID() uint64 {
	if x != nil && x.UserID != nil {
		return *x.UserID
	}
	return 0
}

type ListPermissionsResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Permissions   []*Permission          `protobuf:"bytes,1,rep,name=permissions" json:"permissions,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListPermissionsResponse) Reset() {
	*x = ListPermissionsResponse{}
	mi := &file_grpc_user_service_proto_msgTypes[18]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListPermissionsResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListPermissionsResponse) ProtoMessage() {}

func (x *ListPermissionsResponse) ProtoReflect() protoreflect.Message {
	mi := &file_grpc_user_service_proto_msgTypes[18]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListPermissionsResponse.ProtoReflect.Descriptor instead.
func (*ListPermissionsResponse) Descriptor() ([]byte, []int) {
	return file_grpc_user_service_proto_rawDescGZIP(), []int{18}
}

func (x *ListPermissionsResponse) GetPermissions() []*Permission {
	if x != nil {
		return x.Permissions
	}
	return nil
}

type UpdatePermissionsRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	UserID        *uint64                `protobuf:"varint,1,opt,name=userID" json:"userID,omitempty"`
	Permissions   []*Permission          `protobuf:"bytes,2,rep,name=permissions" json:"permissions,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *UpdatePermissionsRequest) Reset() {
	*x = UpdatePermissionsRequest{}
	mi := &file_grpc_user_service_proto_msgTypes[19]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UpdatePermissionsRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UpdatePermissionsRequest) ProtoMessage() {}

func (x *UpdatePermissionsRequest) ProtoReflect() protoreflect.Message {
	mi := &file_grpc_user_service_proto_msgTypes[19]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UpdatePermissionsRequest.ProtoReflect.Descriptor instead.
func (*UpdatePermissionsRequest) Descriptor() ([]byte, []int) {
	return file_grpc_user_service_proto_rawDescGZIP(), []int{19}
}

func (x *UpdatePermissionsRequest) GetUserID() uint64 {
	if x != nil && x.UserID != nil {
		return *x.UserID
	}
	return 0
}

func (x *UpdatePermissionsRequest) GetPermissions() []*Permission {
	if x != nil {
		return x.Permissions
	}
	return nil
}

type UpdatePermissionsResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Permissions   []*Permission          `protobuf:"bytes,1,rep,name=permissions" json:"permissions,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *UpdatePermissionsResponse) Reset() {
	*x = UpdatePermissionsResponse{}
	mi := &file_grpc_user_service_proto_msgTypes[20]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UpdatePermissionsResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UpdatePermissionsResponse) ProtoMessage() {}

func (x *UpdatePermissionsResponse) ProtoReflect() protoreflect.Message {
	mi := &file_grpc_user_service_proto_msgTypes[20]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UpdatePermissionsResponse.ProtoReflect.Descriptor instead.
func (*UpdatePermissionsResponse) Descriptor() ([]byte, []int) {
	return file_grpc_user_service_proto_rawDescGZIP(), []int{20}
}

func (x *UpdatePermissionsResponse) GetPermissions() []*Permission {
	if x != nil {
		return x.Permissions
	}
	return nil
}

var File_grpc_user_service_proto protoreflect.FileDescriptor

const file_grpc_user_service_proto_rawDesc = "" +
	"\n" +
	"\x17grpc/user-service.proto\x1a\x1bgoogle/protobuf/empty.proto\"\x98\x01\n" +
	"\bLocation\x12\x12\n" +
	"\x04name\x18\x01 \x01(\tR\x04name\x12\x16\n" +
	"\x06street\x18\x02 \x01(\tR\x06street\x12\"\n" +
	"\fstreetNumber\x18\x03 \x01(\rR\fstreetNumber\x12\x18\n" +
	"\acountry\x18\x04 \x01(\tR\acountry\x12\"\n" +
	"\ffederalState\x18\x05 \x01(\tR\ffederalState\"Z\n" +
	"\n" +
	"Permission\x12\x16\n" +
	"\x06userID\x18\x01 \x01(\x04R\x06userID\x12\x1c\n" +
	"\tprojectID\x18\x02 \x01(\x04R\tprojectID\x12\x16\n" +
	"\x06RoleID\x18\x03 \x01(\x04R\x06RoleID\"*\n" +
	"\x04Role\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\x04R\x02id\x12\x12\n" +
	"\x04name\x18\x02 \x01(\tR\x04name\"{\n" +
	"\x04User\x12\x1a\n" +
	"\busername\x18\x01 \x01(\tR\busername\x12\x14\n" +
	"\x05email\x18\x02 \x01(\tR\x05email\x12\x1a\n" +
	"\bpassword\x18\x03 \x01(\tR\bpassword\x12%\n" +
	"\blocation\x18\x04 \x01(\v2\t.LocationR\blocation\"I\n" +
	"\x11CreateUserRequest\x12\x19\n" +
	"\x04user\x18\x01 \x01(\v2\x05.UserR\x04user\x12\x19\n" +
	"\x04role\x18\x02 \x01(\v2\x05.RoleR\x04role\"/\n" +
	"\x12CreateUserResponse\x12\x19\n" +
	"\x04user\x18\x01 \x01(\v2\x05.UserR\x04user\"(\n" +
	"\x0eGetUserRequest\x12\x16\n" +
	"\x06userID\x18\x01 \x01(\x04R\x06userID\",\n" +
	"\x0fGetUserResponse\x12\x19\n" +
	"\x04user\x18\x01 \x01(\v2\x05.UserR\x04user\"\x84\x01\n" +
	"\x11UpdateUserRequest\x12\x16\n" +
	"\x06userID\x18\x01 \x01(\x04R\x06userID\x12\x14\n" +
	"\x05email\x18\x02 \x01(\tR\x05email\x12\x1a\n" +
	"\bpassword\x18\x03 \x01(\tR\bpassword\x12%\n" +
	"\blocation\x18\x04 \x01(\v2\t.LocationR\blocation\"/\n" +
	"\x12UpdateUserResponse\x12\x19\n" +
	"\x04user\x18\x01 \x01(\v2\x05.UserR\x04user\"+\n" +
	"\x11DeleteUserRequest\x12\x16\n" +
	"\x06userID\x18\x01 \x01(\x04R\x06userID\"0\n" +
	"\x12DeleteUserResponse\x12\x1a\n" +
	"\busername\x18\x01 \x01(\tR\busername\"0\n" +
	"\x12CreateRolesRequest\x12\x1a\n" +
	"\brolename\x18\x01 \x01(\tR\brolename\"0\n" +
	"\x13CreateRolesResponse\x12\x19\n" +
	"\x04role\x18\x01 \x01(\v2\x05.RoleR\x04role\"0\n" +
	"\x11ListRolesResponse\x12\x1b\n" +
	"\x05roles\x18\x01 \x03(\v2\x05.RoleR\x05roles\"H\n" +
	"\x12UpdateRolesRequest\x12\x16\n" +
	"\x06roleID\x18\x01 \x01(\x04R\x06roleID\x12\x1a\n" +
	"\broleName\x18\x02 \x01(\x04R\broleName\"0\n" +
	"\x13UpdateRolesResponse\x12\x19\n" +
	"\x04role\x18\x01 \x01(\v2\x05.RoleR\x04role\"0\n" +
	"\x16ListPermissionsRequest\x12\x16\n" +
	"\x06userID\x18\x01 \x01(\x04R\x06userID\"H\n" +
	"\x17ListPermissionsResponse\x12-\n" +
	"\vpermissions\x18\x01 \x03(\v2\v.PermissionR\vpermissions\"a\n" +
	"\x18UpdatePermissionsRequest\x12\x16\n" +
	"\x06userID\x18\x01 \x01(\x04R\x06userID\x12-\n" +
	"\vpermissions\x18\x02 \x03(\v2\v.PermissionR\vpermissions\"J\n" +
	"\x19UpdatePermissionsResponse\x12-\n" +
	"\vpermissions\x18\x01 \x03(\v2\v.PermissionR\vpermissions2\x9e\x04\n" +
	"\vUserService\x125\n" +
	"\n" +
	"CreateUser\x12\x12.CreateUserRequest\x1a\x13.CreateUserResponse\x12,\n" +
	"\aGetUser\x12\x0f.GetUserRequest\x1a\x10.GetUserResponse\x125\n" +
	"\n" +
	"UpdateUser\x12\x12.UpdateUserRequest\x1a\x13.UpdateUserResponse\x125\n" +
	"\n" +
	"DeleteUser\x12\x12.DeleteUserRequest\x1a\x13.DeleteUserResponse\x127\n" +
	"\n" +
	"CreateRole\x12\x13.CreateRolesRequest\x1a\x14.CreateRolesResponse\x127\n" +
	"\tListRoles\x12\x16.google.protobuf.Empty\x1a\x12.ListRolesResponse\x128\n" +
	"\vUpdateRoles\x12\x13.UpdateRolesRequest\x1a\x14.UpdateRolesResponse\x12D\n" +
	"\x0fListPermissions\x12\x17.ListPermissionsRequest\x1a\x18.ListPermissionsResponse\x12J\n" +
	"\x11UpdatePermissions\x12\x19.UpdatePermissionsRequest\x1a\x1a.UpdatePermissionsResponseB-Z+github.com/KingKeleos/photopro-user-serviceb\beditionsp\xe8\a"

var (
	file_grpc_user_service_proto_rawDescOnce sync.Once
	file_grpc_user_service_proto_rawDescData []byte
)

func file_grpc_user_service_proto_rawDescGZIP() []byte {
	file_grpc_user_service_proto_rawDescOnce.Do(func() {
		file_grpc_user_service_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_grpc_user_service_proto_rawDesc), len(file_grpc_user_service_proto_rawDesc)))
	})
	return file_grpc_user_service_proto_rawDescData
}

var file_grpc_user_service_proto_msgTypes = make([]protoimpl.MessageInfo, 21)
var file_grpc_user_service_proto_goTypes = []any{
	(*Location)(nil),                  // 0: Location
	(*Permission)(nil),                // 1: Permission
	(*Role)(nil),                      // 2: Role
	(*User)(nil),                      // 3: User
	(*CreateUserRequest)(nil),         // 4: CreateUserRequest
	(*CreateUserResponse)(nil),        // 5: CreateUserResponse
	(*GetUserRequest)(nil),            // 6: GetUserRequest
	(*GetUserResponse)(nil),           // 7: GetUserResponse
	(*UpdateUserRequest)(nil),         // 8: UpdateUserRequest
	(*UpdateUserResponse)(nil),        // 9: UpdateUserResponse
	(*DeleteUserRequest)(nil),         // 10: DeleteUserRequest
	(*DeleteUserResponse)(nil),        // 11: DeleteUserResponse
	(*CreateRolesRequest)(nil),        // 12: CreateRolesRequest
	(*CreateRolesResponse)(nil),       // 13: CreateRolesResponse
	(*ListRolesResponse)(nil),         // 14: ListRolesResponse
	(*UpdateRolesRequest)(nil),        // 15: UpdateRolesRequest
	(*UpdateRolesResponse)(nil),       // 16: UpdateRolesResponse
	(*ListPermissionsRequest)(nil),    // 17: ListPermissionsRequest
	(*ListPermissionsResponse)(nil),   // 18: ListPermissionsResponse
	(*UpdatePermissionsRequest)(nil),  // 19: UpdatePermissionsRequest
	(*UpdatePermissionsResponse)(nil), // 20: UpdatePermissionsResponse
	(*emptypb.Empty)(nil),             // 21: google.protobuf.Empty
}
var file_grpc_user_service_proto_depIdxs = []int32{
	0,  // 0: User.location:type_name -> Location
	3,  // 1: CreateUserRequest.user:type_name -> User
	2,  // 2: CreateUserRequest.role:type_name -> Role
	3,  // 3: CreateUserResponse.user:type_name -> User
	3,  // 4: GetUserResponse.user:type_name -> User
	0,  // 5: UpdateUserRequest.location:type_name -> Location
	3,  // 6: UpdateUserResponse.user:type_name -> User
	2,  // 7: CreateRolesResponse.role:type_name -> Role
	2,  // 8: ListRolesResponse.roles:type_name -> Role
	2,  // 9: UpdateRolesResponse.role:type_name -> Role
	1,  // 10: ListPermissionsResponse.permissions:type_name -> Permission
	1,  // 11: UpdatePermissionsRequest.permissions:type_name -> Permission
	1,  // 12: UpdatePermissionsResponse.permissions:type_name -> Permission
	4,  // 13: UserService.CreateUser:input_type -> CreateUserRequest
	6,  // 14: UserService.GetUser:input_type -> GetUserRequest
	8,  // 15: UserService.UpdateUser:input_type -> UpdateUserRequest
	10, // 16: UserService.DeleteUser:input_type -> DeleteUserRequest
	12, // 17: UserService.CreateRole:input_type -> CreateRolesRequest
	21, // 18: UserService.ListRoles:input_type -> google.protobuf.Empty
	15, // 19: UserService.UpdateRoles:input_type -> UpdateRolesRequest
	17, // 20: UserService.ListPermissions:input_type -> ListPermissionsRequest
	19, // 21: UserService.UpdatePermissions:input_type -> UpdatePermissionsRequest
	5,  // 22: UserService.CreateUser:output_type -> CreateUserResponse
	7,  // 23: UserService.GetUser:output_type -> GetUserResponse
	9,  // 24: UserService.UpdateUser:output_type -> UpdateUserResponse
	11, // 25: UserService.DeleteUser:output_type -> DeleteUserResponse
	13, // 26: UserService.CreateRole:output_type -> CreateRolesResponse
	14, // 27: UserService.ListRoles:output_type -> ListRolesResponse
	16, // 28: UserService.UpdateRoles:output_type -> UpdateRolesResponse
	18, // 29: UserService.ListPermissions:output_type -> ListPermissionsResponse
	20, // 30: UserService.UpdatePermissions:output_type -> UpdatePermissionsResponse
	22, // [22:31] is the sub-list for method output_type
	13, // [13:22] is the sub-list for method input_type
	13, // [13:13] is the sub-list for extension type_name
	13, // [13:13] is the sub-list for extension extendee
	0,  // [0:13] is the sub-list for field type_name
}

func init() { file_grpc_user_service_proto_init() }
func file_grpc_user_service_proto_init() {
	if File_grpc_user_service_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_grpc_user_service_proto_rawDesc), len(file_grpc_user_service_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   21,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_grpc_user_service_proto_goTypes,
		DependencyIndexes: file_grpc_user_service_proto_depIdxs,
		MessageInfos:      file_grpc_user_service_proto_msgTypes,
	}.Build()
	File_grpc_user_service_proto = out.File
	file_grpc_user_service_proto_goTypes = nil
	file_grpc_user_service_proto_depIdxs = nil
}
